drop table MEMBERS;

CREATE TABLE MEMBERS(
    MNO NUMBER NOT NULL
,   EMAIL VARCHAR2(40) NOT NULL
,   PWD VARCHAR2(100) NOT NULL
,   MNAME VARCHAR2(50) NOT NULL
,   CRE_DATE DATE NOT NULL
,   MOD_DATE DATE NOT NULL
);


COMMENT ON TABLE MEMBERS IS '회원기본정보';
COMMENT ON COLUMN MEMBERS.MNO IS '회원번호';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.PWD IS '암호';
COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
COMMENT ON COLUMN MEMBERS.CRE_DATE IS '가입일';
COMMENT ON COLUMN MEMBERS.MOD_DATE IS '마지막정보변경일';

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_MNO_PK PRIMARY KEY(MNO);

ALTER TABLE MEMBERS
ADD CONSTRAINT MEMBERS_EMAIL_UK UNIQUE(EMAIL);

DROP SEQUENCE MEMBERS_MNO_SEQ;
CREATE SEQUENCE MEMBERS_MNO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO MEMBERS
(mno,email, pwd, mname, cre_date, mod_date )
VALUES(members_mno_seq.nextval, 'SL1@TEST.COM', '1111', '홍길동', SYSDATE, SYSDATE);

INSERT INTO MEMBERS
(mno,email, pwd, mname, cre_date, mod_date )
VALUES(members_mno_seq.nextval, 'SL2@TEST.COM', '1111', '임꺽정', SYSDATE, SYSDATE);

INSERT INTO MEMBERS
(mno,email, pwd, mname, cre_date, mod_date )
VALUES(members_mno_seq.nextval, 'SL3@TEST.COM', '1111', '일지매', SYSDATE, SYSDATE);

INSERT INTO MEMBERS
(mno,email, pwd, mname, cre_date, mod_date )
VALUES(members_mno_seq.nextval, 'SL4@TEST.COM', '1111', '이몽룡', SYSDATE, SYSDATE);

INSERT INTO MEMBERS
(mno,email, pwd, mname, cre_date, mod_date )
VALUES(members_mno_seq.nextval, 'SL5@TEST.COM', '1111', '성춘향', SYSDATE, SYSDATE);

SELECT * FROM MEMBERS;

COMMIT;
